### PR TITLE
missed metafields methods

### PR DESCRIPTION
**Pull request by savchukoleksii**
I added some methods for metafields. 
Some resources has metafield resources, but not all. I think that a good idea to make all resources same. Last thing that I dont know how to do:
I dont know how to implement Product Image metafields resourse. Any ideas?

### CODE REVIEW

**Comment by savchukoleksii** [comment]
Hi, @bakura10
Can you please review my code?

**Comment by Orkin** [comment]
Hi @savchukoleksii @bakura10 is not reviewing this project anymore but @Ocramius can do it and I think he can merge too if it's ok 😉

**Comment by savchukoleksii** [comment]
@Orkin Thank you for information. I added @Ocramius for review.

**Comment by bakura10** [comment]
I will review up. It looks ok. Could you please add this to the changelog? (make sure to pull the last code)

**Comment by savchukoleksii** [comment]
@bakura10 ok. I will do it today.
@bakura10 any ideas how to do Product Image resource?

**Comment by bakura10** [comment]
I'm having a lot of hard time seeing the use case for metafields in product image. Do you have an example of real-life use case? I'm quite curious about this.

**Comment by savchukoleksii** [comment]
@bakura10 I think we need to ask Shopify about this))
So for this time can skip this method)

**Comment by savchukoleksii** [comment]
@bakura10 I add changelog

**Comment by bakura10** [comment]
Thanks. This has been tagged.

**Pull request merged**
