### PR TITLE
Add Customer Addresses

### PR DESCRIPTION
**Pull request by efficientbit**
Customer addresses related api endpoints are added.

### CODE REVIEW

**Comment by efficientbit** [comment]
@bakura10 kindly review and merge these endpoints.

**Comment by bakura10** [comment]
Looks good! Can you please add the methods here: https://github.com/zf-fr/zfr-shopify#implemented-endpoints and update teh changelog?

**Comment by efficientbit** [comment]
@bakura10 I have added endpoints in the provided area already. Regarding the changelog, I didn't put the info here as I believe you are handling version numbers, etc.

**Comment by bakura10** [comment]
Thanks for your contribution. This has been tagged as 6.3.0

**Comment by efficientbit** [comment]
Thanks for adding and labeling.

**Comment by efficientbit** [comment]
@bakura10 can you draft a release as well? I've fetched code and still unable to use new endpoints. Current release v.6.2.1 doesn't have these endpoints.

**Comment by bakura10** [comment]
My bad. This is done!

**Comment by efficientbit** [comment]
@bakura10 thanks for the release. 

Would you like to add me to this team as "maintainer"? I would like to maintain this library in case your are not available. we are heavily depending on this library for our own and clients' apps. 

Our Apps:
apps.shopify.com/partners/developify-solutions

**Comment by bakura10** [comment]
Thanks a lot for the offer :).

ZfrShopify is also used extensively by apps of my previous company (Maestrooo). Although I left I maintain this library so I would need the approval of Maestrooo to add a third-party maintainer. For now I think it's easier that I deal with it but feel free to submit PR, I'll be happy to quickly review them.

**Comment by efficientbit** [comment]
Hi @bakura10 
Please ask them. We are also Shopify Partners and we're happy to collaborate with Maestroo to maintain this library. You are the only maintainer or there is another team player maintaining this library? If yes, then there is no need to add me :) If no, then you better add any person from Maestroo or me or anyone else who could maintain it with you. I hope you can understand what I mean :)

**Comment by bakura10** [comment]
Yes, I understand :). Actually @fabiensebban from Maestrooo also uses this library so he can maintain it in case of trouble! But thanks for the offer, I'll definitely keep it in mind if I can't maintain it anymore.

**Pull request merged**
